### ISSUE TITLE
Wrong Magic Find

### ISSUE THREAD

**Issue by Frosty0204** [carreb/meterthing#4]
![image](https://github.com/carreb/meterthing/assets/164660294/9c16f87b-0813-4431-b70a-5a04081a4375)

This it shows 223 mf but I have 270

**Comment by t4ttc** [comment]
weird, keep doing bosses and see if it updates. it's supposed to update whenever you get a rare drop (as that is when magic find is visible), if it's not working still, try running `/CT reload`, if it still doesn't work, run `/ct console js`, and do bosses until you get a rare drop, then reply to this with anything that shows up in the console

**Comment by carreb** [comment]
weird, keep doing bosses and see if it updates. it's supposed to update whenever you get a rare drop (as that is when magic find is visible), if it's not working still, try running `/CT reload`, if it still doesn't work, run `/ct console js`, and do bosses until you get a rare drop, then reply to this with anything that shows up in the console

**Comment by t4ttc** [comment]
can't replicate + no follow up, re-open if you are still having this problem and follow the instructions above @Frosty0204
